### ISSUE TITLE
Neo Hub, Neostat and NeoUltra - can't see temperatures

### ISSUE THREAD

**Issue by hollytreecook** [MindrustUK/Heatmiser-for-home-assistant#125]
Hi
I have NeoStat V2s (16 number), NeoUltra and NeoHub.
Everything is the wired version. 
I can connect to the Heatmiser Neo Climate and see 16 devices and 16 entities.
They all appear to be switches, but I cannot see any temperatures for each room.
Any ideas please?
Thanks
![Screenshot 2023-04-25 121400](https://user-images.githubusercontent.com/131459314/234292776-4ed85578-4027-4115-8c60-4f52b74edf8c.png)

**Comment by MindrustUK** [comment]
Can you open a terminal (There's an addon in home-assistant if required to provide this if you need it) and run the following two commands substituting <NEOHUB_IP_HERE> with your IP Address;

Note these could expose personal information so please review carefully before posting the output.

printf '{"INFO":0}\0' | nc <NEOHUB_IP_HERE> 4242

printf '{"GET_LIVE_DATA": 0}\0' | nc <NEOHUB_IP_HERE> 4242

This will hopefully highlight why the devices are appearing as time switches. I'm thinking it could be because your stats are configured as time clocks?

**Comment by hollytreecook** [comment]
typed in but nothing happened. 
Error in text the 1st time
![Screenshot 2023-04-25 152033](https://user-images.githubusercontent.com/131459314/234306760-bfe89f79-aea5-42d7-b1b0-708b30f2335b.png)

**Comment by MindrustUK** [comment]
Try:

printf '{"INFO":0}\0' | nc 192.168.1.99 4242

printf '{"GET_LIVE_DATA": 0}\0' | nc 192.168.1.99 4242

**Comment by hollytreecook** [comment]
Thanks.
Is there a way to copy text from a browser page into terminal page?

**Comment by hollytreecook** [comment]
![Screenshot 2023-04-25 153716](https://user-images.githubusercontent.com/131459314/234311752-5c3fc195-5eec-414f-af35-a5840af6ef45.png)

**Comment by MindrustUK** [comment]
Space between printf and '

You can copy and paste into the terminal by middle clicking on Linux try right click on Windows I guess, on Mac no idea.

M.

**Comment by hollytreecook** [comment]
right. Thanks put the space in the info command (1st one) and got tons of lines of text Pretty much everything says false

**Comment by MindrustUK** [comment]
Yup that's as expected, if you can paste that block so we can check through it and see what the behaviour is.

**Comment by hollytreecook** [comment]
Thanks. How Do I paste the block?

**Comment by hollytreecook** [comment]
![Screenshot 2023-04-25 163235](https://user-images.githubusercontent.com/131459314/234328071-d73cc302-968b-4c21-bdea-b7b374ab03bc.png)

**Comment by MindrustUK** [comment]
Can you post a screen shot of the "entities" for the Heatmiser intergeneration?

**Comment by hollytreecook** [comment]
Hi. That's the entities as they appear now
![Screenshot 2023-04-26 124158](https://user-images.githubusercontent.com/131459314/234564649-ad0dc92f-bf59-40a2-8976-3143cafe1407.jpg)

**Comment by MindrustUK** [comment]
Odd, very odd... things like the hall are showing up as climate devices, where as hot water is showing up as a switch. That's expected. Home Assistant is identifying the devices correctly so I'm not sure as to why they would ALL appear as switches given that they are displaying here as climate... can you confirm that clicking on any of the entities brings up dialogue with temperature and mode options? I'm wondering if this is something to do with your dashboard setup rather than the intergeneration as so far everything seems to be behaving as expected.

**Comment by hollytreecook** [comment]
I created a new card and put them all in.
If I go into one of them and click the history I see the temperature curve
![Screenshot 2023-04-26 131900](https://user-images.githubusercontent.com/131459314/234572821-2c808183-7d80-4537-b589-504e84f930da.jpg)

![Screenshot 2023-04-26 131937](https://user-images.githubusercontent.com/131459314/234572858-9dd3b940-b02f-4cdd-9f8a-6887c6c81bef.jpg)

**Comment by hollytreecook** [comment]
I added a thermostat card for a single room, but when I added "Custom:mini graph card" and tried to put in a room, the second snip is what I get. I have no idea what NaN is?
![Screenshot 2023-04-26 143816](https://user-images.githubusercontent.com/131459314/234596219-8d7a61e3-c0c4-4d22-bb55-4ee7eb656d23.png)
![Screenshot 2023-04-26 144626](https://user-images.githubusercontent.com/131459314/234596272-4603ca24-989b-47a5-b59b-590d129491f4.png)

**Comment by hollytreecook** [comment]
I think I have got as far as this with Custom:mini:graph and will try and improve my skills.
Thanks for all the help
Steve
