### ISSUE TITLE
2nd Generation Heatmiser Neo Hub support?

### ISSUE THREAD

**Issue by ando2040** [MindrustUK/Heatmiser-for-home-assistant#169]
I'm struggling with this hardware (2nd Generation Heatmiser Neo.) Keying in this IP on port 4242 under Heatmiser Neo integration setup wizard just kicks back. It self-identifies as Aqara Hub M2 - is it a new OEM?

![image](https://github.com/user-attachments/assets/11f8f238-561d-4162-aa62-804e7a6748ef)

![image](https://github.com/user-attachments/assets/110647e2-4699-4615-9924-aeec76d0d617)

**Comment by MindrustUK** [comment]
Hi @ando2040 Ubiquiti I see, the problem is that Ubiquiti resolve their manufactures by MAC address and don't get it right all the time.

I suspect the most likely reason you're having trouble is that you haven't enabled "Legacy API" in the Heatmiser App.
On Android if you open the app -> login to your heating setup / home -> Settings (Cog Wheel in the lower right corner) -> API and toggle "Legacy API" on everything should start working.

Can you confirm this has been done and if if works or not?

**Comment by ando2040** [comment]
Apologies for the noddy question - yep that fixed it.
