### ISSUE TITLE
Integration stopped working after update

### ISSUE THREAD

**Issue by david-b13** [MindrustUK/Heatmiser-for-home-assistant#188]
Wonder if you can help….

the integration seems to have stopped working after latest update.  I have reboot the new hub and my HA instance, to no effect.  The neoliberal and thermostats seem to be work8ng fine, it’s just thatHA can’t see them.  I have checked the legacy API is still “on”.

Neohub shows 3 green lights.

any suggestions ?

**Comment by bonstio** [comment]
I observe what I think is the same. All devices are unavailable in HA. No amount of power cycling. The 'enable legacy' setting was (and remains) enabled and the native app works fine.

I hesitate to install what's in the dev branch because a) the integration has been rock solid until this and b) it's a hassle to rewire many dashboards.

**Comment by aelking** [comment]
The integration on my end has readded the devices with new device ids. Could this be the issue for you?

**Comment by MindrustUK** [comment]
Hi @aelking device ID's we're re-written as part of change log: 20240928 as you've stated, this is due to non-unique ID's previously being included which caused all sorts of broken behaviours. These have now been fixed, unfortunately it means that devices are either missing or replaced / duplicated and some clean-up is needed.

@david-b13 @bonstio I suggest checking the logs for errors, and doing a clean reinstall the integration. I've updated the readme with various troubleshooting tips to assist but feel free to reply here if you don't get anywhere and I'll do my best to help.

**Comment by bonstio** [comment]
Thanks, @aelking and @MindrustUK 

This was exactly it in my case. Many thanks. Reinstall and minor card changes has got me back on track. I am grateful! :-)

**Comment by david-b13** [comment]
Reinstalled and now working again.  Many thanks.  Why did it need that ?

**Comment by MindrustUK** [comment]
Hi @david-b13 As per https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/188#issuecomment-2427131908 the Unique device ID's were re-written.

It looks like the issue has been resolved by adopting new ID's closing issue. Please pay special attention to anything marked as "Breaking" in the change log etc.
