### ISSUE TITLE
NeoStat not working after the update

### ISSUE THREAD

**Issue by marcuscps** [MindrustUK/Heatmiser-for-home-assistant#189]
My Secondary Water pump switch entity is not getting recognised anymore after the update.
I get these entities:

```
sensor.secondary_pump_heatmiser_neostat_v2_timer_output_active
switch.secondary_pump_heatmiser_neostat_v2_standby
sensor.secondary_pump_heatmiser_neostat_v2_hold_time_remaining
sensor.secondary_pump_heatmiser_neostat_v2_hold_active
sensor.secondary_pump_heatmiser_neostat_v2_device_connectivity
button.secondary_pump_heatmiser_neo_identify_device
```

I was hoping to get a switch to turn it on manually. Am I getting it wrong?

Thanks

**Comment by PhillyGilly** [comment]
Similar problem here. I use NeoStats in clock mode to control the Hot Water function in my Central Heating and Towel Rails in my bathrooms.  As well as the devices running programmes autonomously, I have a number of automations which used the legacy switch function to the Neostats e.g. heat the towel rails only using the two cheapest Agile slots.
I assume that the switch function should be superseded by an action (service call) like the "Heatmiser Neo Climate: Temperature Hold On" maybe: "Heatmiser NeoStat: Turn on" and "Heatmiser NeoStat: Turn off".
With the legacy "switch" function, my NeoStats always turned off after 30mins, so there might be a more sophisticated option which mimics the over-ride function in the app, but I like to be able to switch off on a trigger so I don't know if that would add value.
Can I request that this is added in urgently as my towels are a bit damp :-) 
Thanks.

**Comment by marcuscps** [comment]
The **Temperature Hold** function doesn't seen to be suitable for my case. There is no Temperature to be measured or set in my case as the NeoStat is just acting as a Relay to turn the Pump On/Off.

I know I could replace the NeoStat v2 that controls the Secondary Pump with a Relay. However that would make the Heating System more disconnected with most of the Heating controlled from Heatmiser and the Relay controlled from HomeAssistant. I'd prefer to avoid it.

The Heatmiser App itself is a bit confusing IMHO. It has 3 modes: Auto, Override, StandBy.

In the **Auto mode** if follows a schedule, but in the absence of it, it would simply stay in the last state set: On or Off. This is what I've been using.
In the **Override mode** it would disable the Schedule for a given time, forcing it On or Off.
I'm not sure I understand the **StandBy mode**. I suppose it is simply a glorified name for "stay off". Is it the correct understanding?

**Comment by MindrustUK** [comment]
Please check out: https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/182 there's some on going work here to restore functionality similar to the version 1 branch.

**Comment by MindrustUK** [comment]
Hi @marcuscps It looks like the great work done by @ocrease in the afore mentioned thread should resolve your issue. However your comments about modes has sparked an idea for implementation in the dev branch. Can you confirm for now your issue is resolved?

**Comment by marcuscps** [comment]
Hi @MindrustUK . It got resolved. Thanks a lot for addressing it!

The name of the switch entity is different than before, but that's fine.

I particularly think it is a bit strange there is no way to force it ON as I can do it from the Heatmiser App (auto mode, click on without a schedule). But I worked around it.

I'm curious about the idea I sparked. I'd be more than happy to contribute.

**Comment by ocrease** [comment]
@marcuscps I think @MindrustUK is referring to the ability to add an override to OFF. My PR just reintroduced the ability to use the switch to set an Override ON for 30 minutes like in the previous version. However I've also added a service (Timer Hold On) so you can set a different duration. 

![image](https://github.com/user-attachments/assets/c819a719-1a4f-4eed-825c-ffd757351eec)

If you want to remove the hold you can use the standard `Switch: Turn off` action.

Is the ability to override to OFF (eg if the schedule has the timer active and you want to force it to be off) something you are interested in? I think it should be added, the question is how important it is. Either way it's a feature that would need to be added on the dev branch rather than the current version.

Regarding forcing the timer to ON, I tried on mine via the app and the behaviour I saw is as follows:

- If the schedule is currently off and I select ON from the Auto mode, it actually sets an Override ON for 1h.
- If the schedule is currently on and I select OFF from the Auto Mode, it sets an Override OFF for 1h.

 To actually see this you have to go back to the home page and then go back into the relevant stat and you'll see the screen is now in Override rather than Auto. Is that different to your experience?

**Click On from Auto**
![image](https://github.com/user-attachments/assets/adfa0ce3-b34c-4f1e-a561-260c78a36975)

**Go back in and now in Override**
![image](https://github.com/user-attachments/assets/25c350d0-1bf7-4fd5-af66-1efd8394a480)

I think the closest you can get currently is to use the Timer Hold On service with a large duration. I'm not sure what the maximum is, I believe either 8 or 99 hours.

**Comment by marcuscps** [comment]
@ocrease I don't particularly need the ability to Override to OFF as my setup is quite simple here.

This current Heatmiser app behaviour you described is not very intuitive IMHO. But reality imposes, right? :D 
My understanding is their UI is not reactive at all and creates a lot of confusion.

I just tested it carefully without a schedule, and seems to match your understanding:

1 - Initially OFF
![Screenshot_20241024-163020](https://github.com/user-attachments/assets/99d2796a-71fc-40cb-8ec0-9f0a34e58874)
![Screenshot_20241024-163042](https://github.com/user-attachments/assets/5d8d28fb-549c-484e-b415-0a0f82b2eac8)

2 - Then I click ON on the AUTO mode.
![Screenshot_20241024-163051](https://github.com/user-attachments/assets/c8a50dec-5c18-4c3b-ab62-18adbdb148ce)

3 - Override set to 1h
Funny enough, the UI is not reactive enough, and will not update indeed. So if refresh the UI (to to home and back), and confirm the Override is set.
![Screenshot_20241024-163108](https://github.com/user-attachments/assets/e0c41a39-2761-451b-a156-8e06c0050a87)
![Screenshot_20241024-163104](https://github.com/user-attachments/assets/a3132f3e-93c3-4397-81f0-4a01f23ce1a4)

4 - Cancel the Override
If I cancel the Override by sliding it to Zero, and clicking DONE
![Screenshot_20241024-163120](https://github.com/user-attachments/assets/994cae94-544b-4f70-a415-57b2e8df5673)
![Screenshot_20241024-163125](https://github.com/user-attachments/assets/358e7a50-da26-40e6-9743-685fbff6912d)

Funny enough, the UI doesn't update at all. And still says ON.

![Screenshot_20241024-163125](https://github.com/user-attachments/assets/f7c98452-278d-4776-b77f-227051d5a240)

5 - Refreshing the UI and confirming the Override has been cancelled:
![Screenshot_20241024-163136](https://github.com/user-attachments/assets/b95de83e-6b8f-42e3-bdee-ba426bfee4ed)

**Comment by MindrustUK** [comment]
This may bleed into another area which is clearing the profile in the timers and schedules...

@marcuscps It feels like you're exploiting a mode of operation that clearly works but may not have been intended by the software developers. Because there is no schedule when you change state the device just effectively hangs and doesn't do anything else. While this works for you, it's probably not what Heatmiser was intending to be the use case. Regardless I'd like to have some manual operation so I'm not dismissing your request or requirement but it's going to need some thinking as to how best to achieve it without "Exploiting" the system.

The NeoPlugs for example have a manual mode that disables the timer. I'm wondering if we ask on the dev forum nicely would Heatmiser add this to the API, they've been pretty hit and miss at replying to my other posts. We can at least ask and go from there.

**Comment by marcuscps** [comment]
Sounds like a plan.
BTW, I'd love to contribute if you need any help. I'm a software engineer with plenty of experience. I never contributed to anything home assistant, but would love to.

**Comment by MindrustUK** [comment]
@marcuscps the more help on the project the better. I'm not going to refuse. I've started a project board for the various bits outstanding or if there's anything you want to contribute to please feel free to get stuck in and raise pull requests against the dev branch. The Heatmiser Developer portal is here: https://dev.heatmiser.com/ maybe start with your use case for manual operation and see if you can make anything of that?

**Comment by marcuscps** [comment]
@MindrustUK Will have a look this weekend.
Thanks a lot.

**Comment by ocrease** [comment]
@MindrustUK @marcuscps I've been thinking about this again. I think once the hold functionality is implemented in #201, you'll be able to do everything you need. Might even be possible now. 

If you don't want the heatmiser app to handle schedules at all I think there are two ways to go:

- If you want the ability to leave the stat on or off for an unlimited time, create and assign a profile with a single step of state ON at 00:00. This will mean that it's always on by default. If you want to turn it off, then set it to standby and it will stay OFF until you say otherwise.
- If instead you want the ability to turn on with a failsafe to turn off again (say HA is down or the automation goes wrong), create a profile with a single step of state OFF and use the override to turn it ON for say 8 hours (or longer than the longest time you want it to be on for). Then you can cancel the hold when you no longer want it ON.

Either way I think having a default schedule on or off would be good to avoid ambiguity.

I don't think there are any changes required to the heatmiser API to support it. If I misunderstood the requirements, let me know!

**Comment by ocrease** [comment]
@MindrustUK does this need to stay open? I think it's fixed in dev?

**Comment by MindrustUK** [comment]
@ocrease agreed. Closing.
