### ISSUE TITLE
Away mode issues

### ISSUE THREAD

**Issue by maa-x** [MindrustUK/Heatmiser-for-home-assistant#23]
Hi,

I am having issues setting the preset mode 'away'. When calling the climate.set_preset_mode with preset_mode set to 'away', I am given the following error:

```

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1236, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 348, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 370, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 431, in async_set_preset_mode
    await self.hass.async_add_executor_job(self.set_preset_mode, preset_mode)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 427, in set_preset_mode
    raise NotImplementedError()
NotImplementedError

```

According to `git log`, I am running the latest version. 

`configuration.yml`:

```
climate:
  - platform: heatmiserneo
    host: <>
    port: <>
```

The state of one of the thermostats:
```
hvac_modes:
  - heat
current_temperature: 24.8
min_temp: 7
max_temp: 35
temperature: 16
current_humidity: 0
hvac_action: idle
friendly_name: Living Room
supported_features: 1
```
Which seems to be missing an 'away_mode' state. 

Furthermore, wondering if there are any other preset_modes other than `away`?

**Comment by MaxIsMyName** [comment]
To add to this, I cannot actually see the thermostats in the entity list from `/config/entity_registry`. They exist and work when I change the temperature but other than that I cannot find anything relating to heatmiserneo. It's rather hard to debug.

**Comment by Trouble-51** [comment]
Away mode doesn't work as it should because it sets ALL thermostats to away mode (in my case all 13!), not just the one(s) that you want to set to away mode.

**Comment by MaxIsMyName** [comment]
Unfortunately, Heatmiser’s Away mode is more like a holiday mode. As a result I’m only using it when I leave for an extended period of time and simply set the temperature of different groups of rooms based on presence (so 17C when people are away for the day and 19C when they get back).

**Comment by Trouble-51** [comment]
Thanks for your email! But when I use “standby” in the app on the phone it only sets the room in question in ”standby” mode. Is this caused by the word away as opposed to standby? There is an option in the app to set all thermostats to away mode under “Home”, but when you go to the individual rooms only the room in question is changed to away mode.

When you go to “Away” on the right hand top you get a screen asking whether this is for all rooms or you can tick one or more rooms.

It would be a real improvement in home assistant for those who have multiple thermostats if the Standby/Away mode could be changed.

Thanks for the good work and hopefully the above can be implemented 

Merry Christmas and a Happy and Healthy 2020

**Comment by MaxIsMyName** [comment]
I really just hacked this together, I have no clue how the API on either HA or Heatmiser works. I’ll see what the Nest integration does and report back.

**Comment by MindrustUK** [comment]
Quick reply, "Real life (tm)" is keeping me very busy at the minute. I opened a previous issue under: [Away mode affecting all thermostats](https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/6). There's some information around away, standby and frost in this.

I'd suggest adding a standby / frost mode as a function of the stat where applicable. I have various ideas around adding other modes to address some other issues raised in the threads. This is also the cleanest way.

On a related note in the merge request the assertion of away is done from modes and not done on the class of the device, i.e. it's an assumed function that may not be available on that particular thermostat / switch device so that will need addressing. If I get 10 minutes over the holidays I'll try and bump this one up the list and fix a few of these but no promises.

Also note the Heatmiser API features are available on request and subject to NDA so it's worth shooting a mail to Heatmiser to get the documentation.

**Comment by Trouble-51** [comment]
Hi MindrustUK, unfortunately I am just a simple user and have no knowledge of API’s etc. I know your time is scarce, but if you can find some to improve this integration that would really be awesome. Merry Christmas and a Happy & Healthy 2020!
