### ISSUE TITLE
HVAC modes -> Presets ??

### ISSUE THREAD

**Issue by PhillyGilly** [MindrustUK/Heatmiser-for-home-assistant#37]
In the annotation in comments on the original climate.py @MindrustUK notes

47 # Heatmiser does support all lots more stuff, but only heat for now.
48 #hvac_modes=[HVAC_MODE_HEAT_COOL, HVAC_MODE_COOL, HVAC_MODE_HEAT, HVAC_MODE_OFF]
49 # **Heatmiser doesn't really have an off mode - standby is a preset - implement later**
50 hvac_modes = [HVAC_MODE_OFF, HVAC_MODE_HEAT]

Consider the Heatmiser Neo-stats here operating as a temperature controllers and comparing HA with the Heatmiser App:
![image](https://user-images.githubusercontent.com/56273663/98586804-2c2b4d80-22c1-11eb-8c3b-e367a0a6088f.png)

I read this as:
Bathroom 1 is in Standby/Away/Frost mode (grey) and isn't on (idle).
Bathroom 2 is following the "bathrooms" profile (orange) and isn't on as the actual temperature is above the set temperature (idle).
Bedrooms 1 & 2 are following the" bedrooms"(orange) profile and actual temperature is below the set temperature (heating)

So we have four possible outcomes grey/orange plus idle/heating. 

The latest climate entity documentation (https://developers.home-assistant.io/docs/core/entity/climate/) identifies built in presets with the option of adding custom presets. The built in presets are:
Name | Description
ECO | Device is running an energy-saving mode
AWAY | Device is in away mode
BOOST | Device turn all valve full up
COMFORT | Device is in comfort mode
HOME | Device is in home mode
SLEEP | Device is prepared for sleep
ACTIVITY | Device is reacting to activity (e.g. movement sensors)

These could be mapped:
grey/idle => AWAY
grey/heating=> ECO
orange/idle => COMFORT
orange/heating => BOOST

I'm not sure how these mappings might work for time clocks. Are they just AWAY or BOOST?
Any views or comments on this?

**Comment by ntompson** [comment]
Hi @PhillyGilly, that comment at line 49 about the NeoStats not having an off mode is mine. Technically it is true: standby just applies an alternative set point (the frost point) and continues to operate as a normal functioning thermostat. Thinking about the climate platform after its rearchitecture a few months back, standby could be implemented as a preset, which is what my PR did a while back.

Since then, I see that the implementation has been changed such that standby is translated to an `hvac_mode`, specifically `HVAC_MODE_OFF`, and I think it is better for it. It's more logical and fits better with how the standard Lovelace cards work. The nice thing is that the frost point gets change if the temperature is adjusted while the NeoStat is `HVAC_MODE_OFF`, which was the only real reason for my previous implementation of standby as a preset.

So I think the current implementation is optimal.

To your suggestion, I get where you are coming from, but I think it would be an unfortunate mix of concerns between platform and GUI behaviour. The NeoStat alternating between heating and idle should not cause the preset to change. It should be relatively easy to achieve what you are looking for with some custom styling in Lovelace.

Oh, and the comment at line 49 really should be removed - it's not relevant anymore.

**Comment by PhillyGilly** [comment]
OK. I can see that using orange/grey instead of state=heat/state=off may have avoided heat/heating confusion but made the whole less clear. So the four possible permutations of operation with my "preset" names are:
off/idle => AWAY
grey/heating=> ECO
heating/idle => COMFORT
heating/heating => BOOST  I'll work on my custom styling and
