### ISSUE TITLE
After using the custom component for 24-48 hours the Neohub locks up

### ISSUE THREAD

**Issue by robeving** [MindrustUK/Heatmiser-for-home-assistant#55]
I'm running the latest version of both home assistant and this repo. After around 24 hours the Neohub will 'lock up' by that I mean:
* It leaves my hone network
* It disconnections from the heating controller (no WiFi symbol)
* It no longer appears in the official app
I don't see any errors in the HASS log that are related.

This is obviously a bug in the Neohub - it shouldn't lock up BUT when the custom component is removed I have no issues and the Neohub never needs to be rebooted.

Any ideas what is happening here?

Is the local API supported by Neohub? Are there any more logs I can collect?

**Comment by robeving** [comment]
I ran:
`while true; do echo -e '{"INFO": 0}\0\r' | nc MYNEOHUBIP -N; done`
on two threads for about an hour whilst changing settings via the app - no lockup

**Comment by PhillyGilly** [comment]
I had two instances of my hub "locking" too. I ignored the first one, but last night at about 23:30 it stopped talking to HA. The first time I didn't associate the problem with HA, the second time I tried running a simple python script to get INFO and it timed out. It appeared to be still working in the App so that displayed temperatures on the App were the same as the Heatmisers values. In both occasions power cycling the neohub resolved the problem.

**Comment by MindrustUK** [comment]
@robeving was there anything further on this? We've had no wider reports of this behavior with other users. I can only suggest you try the regular suspects, ie firmware updates etc. If there's no update in 30 days I will close this issue.

**Comment by i-am-shodan** [comment]
This is something to do with my device. I've now got it on a timer to reboot it twice a day.

**Comment by MindrustUK** [comment]
Closing the issue as this appears to be no fault of the integration.
