### ISSUE TITLE
Away mode affecting all thermostats

### ISSUE THREAD

**Issue by MindrustUK** [MindrustUK/Heatmiser-for-home-assistant#6]
Setting "Away" on any thermostat sets all thermostats to away.
Have also found that turning away mode off does not seem to work.
Tracked down the "away on all" to a faulty Json request. Hope to fix this soon.

**Comment by MindrustUK** [comment]
Json fixed, however adding any form of stat update in the "Update" sub causes the behavior in HASS to break. Very strange, needs more time spent on this.

**Comment by ntompson** [comment]
So having looked at this a bit now, I think I can say that this is by design, although rather odd. Heatmiser has two "away like" modes: Away and Standby. You can see these in the HM smartphone app. 

- Away = put *all* stats into Standby mode
- Standby = put one specific stat into Standby mode

In the API, different language is used:

- `AWAY_ON|OFF` = Away mode
- `FROST_ON|OFF` = Standby mode

Rather stupidly, `AWAY_ON` is issued to a specific stat, but the result is all stats are put into away mode.

On top of that, it is possible to separately set the target temperature while in Standby mode by using the `SET_FROST` command. Handily (confusingly?) this set temperature applies to both Standby and Away modes.

I have started work on implementing the Away and Standby modes. You can see where I've got to in [this compare](https://github.com/ntompson/Heatmiser-for-home-assistant/compare/fix-climate...ntompson:add-presets) (relative to PR #21). Working for me at the moment - will create a PR if it seems stable over the next few days.

**Comment by MindrustUK** [comment]
@ntompson 

Thanks for your recent pull requests, away can be applied per device but as you've stated frost is a better choice. If you've already got the Heatmiser API doc ignore the following.

If you write to Heatmiser they will furnish you with the developer API documentation. I'm not sure I can paste the contents here, but there's a section that covers exactly this behavior and explains that you can set "Away" per device and the difference in setting "Frost"

**Comment by MindrustUK** [comment]
Additional, my change in Json was to handle "Away" per device, which worked fine from a JSON, Heatmiser point of view, however something in HASS didn't like it and I still haven't found the time to look into it as it's lower priority on my list of things to do.

**Comment by MindrustUK** [comment]
Functionality is as intended. Setting Away should affect ALL devices. Standby/Frost should be per device. Closing issues.
